name: CI/CD Workflow

on:

  push:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code

      uses: actions/checkout@v3

    - name: Set up .NET

      uses: actions/setup-dotnet@v3

      with:

        dotnet-version: '7.0.x'

    - name: Build .NET project

      run: dotnet build

    - name: Build Docker image

      run: docker build -t demohelloworldapp .

    - name: Log in to Azure Container Registry

      run: |

        echo "${{ secrets.AZURE_CLIENT_SECRET }}" | docker login demohelloworldregistry.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    - name: Tag and Push Docker image

      run: |

        docker tag demohelloworldapp demohelloworldregistry.azurecr.io/demohelloworldapp:${{ github.sha }}

        docker push demohelloworldregistry.azurecr.io/demohelloworldapp:${{ github.sha }}

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Azure Login

      uses: azure/login@v1

      with:

        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps

      run: |

        az containerapp update \

          --name demoapp \   # Check if this is the correct name of your container app

          --resource-group demoGroup \   # Check if this is the correct resource group

          --image demohelloworldregistry.azurecr.io/demohelloworldapp:${{ github.sha }}

 
