name: Build and Deploy Docker Image

on:

  push:

    branches:

      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v3

    - name: Set up Docker Buildx

      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub

      uses: docker/login-action@v2

      with:

        username: ${{ secrets.DOCKER_USERNAME }}

        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image

      uses: docker/build-push-action@v4

      with:

        push: true

        tags: ${{ secrets.DOCKER_USERNAME }}/demohelloworldapp:latest

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Deploy to Azure Container Apps

      uses: azure/CLI@v2

      with:

        inlineScript: |

          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

          az containerapp update --name demoapp --resource-group demoGroup --image ${{ secrets.DOCKER_USERNAME }}/demohelloworldapp:latest
 
