name: Centralized Deployment Orchestration
on:
  workflow_dispatch:
jobs:
  read_json_file:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      parsed_services: ${{ steps.parse_json.outputs.services }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checking environment
        run: echo "${{env.subscription}}
      - name: Checking owner id
        run: echo ${{ github.event.repository.owner.login }}
      - name: Read JSON File
        id: parse_json
        run: |
          JSON_INPUT=$(cat .github/workflows/services.json)
          echo "JSON Input: $JSON_INPUT"
          SERVICES=$(echo "$JSON_INPUT" | jq -c '.services')
          echo "Extracted Services: $SERVICES"
          echo "services=$SERVICES" >> $GITHUB_OUTPUT
  process_services:
    needs: read_json_file
    runs-on: ubuntu-latest
    steps:
      - name: Show Extracted Services
        run: echo "Services JSON ${{ needs.read_json_file.outputs.parsed_services }}"
      - name: Platform name
        run:  echo "PLATFORM_NAME=${{ github.event.repository.owner.login }}">>$GITHUB_ENV
      - name: Loop Through Services
        run: |
          echo '${{ needs.read_json_file.outputs.parsed_services }}' | jq -c '.[]' | while read service; do
            SERVICE_NAME=$(echo $service | jq -r '.service_name')
            ENV_FILE_PATH=$(echo $service | jq -r '.env_file_path')
            DISPLAY_NAME=$(echo $service | jq -r '.display_name')
            APIM_SERVICE_NAME=$(echo $service | jq -r '.apim_service_name')
            echo "Checking out to $SERVICE_NAME to fetch .env file..."
            echo "platform name $PLATFORM_NAME"
            REPO_URL=https://github.schneider-electric.com/${{ github.event.repository.owner.login }}/$SERVICE_NAME.git
            echo "url $REPO_URL"
            git clone --branch main $REPO_URL
            SWAGGER_URL=$(echo $service | jq -r '.swagger_url')
            echo "service path $service.path"
            echo "Service Name $SERVICE_NAME"
            echo "Environment File Path $ENV_FILE_PATH"
            echo "Display Name $DISPLAY_NAME"
            echo "APIM Service Name $APIM_SERVICE_NAME"
            echo "Swagger URL $SWAGGER_URL"
          done 
