name: Workflow To Test
on:
  workflow_dispatch:
    inputs:
      microservices:
        type: choice
        required: true
        options:
          - asset-management-api
          - cusotmer-management-api
          - site-management-api
      microservices_as_json:
        type: string
        required: true
        description: 'Enter services as json array (e.g., ["service-a","service-b"])'

jobs:
  microservice_check:
    runs-on: ubuntu-latest
    outputs:
      services_json: ${{steps.set-matrix.outputs.SERVICES}}
    steps:
      - name: Check microservice input var
        shell: bash
        run: echo 'data ${{inputs.microservices}}'
      - name: Parse Json Input
        id: set-matrix
        run: echo "SERVICES=$(echo '${{inputs.microservices_as_json}}' | jq -c .)">>$GITHUB_ENV
      - name: Deploy Services
        run: |
          echo "Deploying Service: $SERVICES"
          for SERVICE in $(echo "$SERVICES" | jq -r '.[]'); do
            echo "Deploying Service $SERVICE"
          done
  run_services:
     needs: microservice_check
     runs-on: ubuntu-latest
     strategy:
       matrix:
         service: ${{ needs.microservice_check.outputs.services_json }}
     steps:
       - name: show service name
         run: echo "service ${{matrix.service}}
